# Generated by Django 4.1.5 on 2023-05-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('service_time', models.TimeField()),
            ],
        ),
    ]
