# Generated by Django 4.1.5 on 2023-05-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
