# Generated by Django 4.1.5 on 2023-05-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0002_alter_service_list_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
                ('service_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ser_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ser_name', models.CharField(max_length=255)),
                ('ser_duration', models.IntegerField()),
                ('ser_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='bellitaweb.category')),
            ],
        ),
    ]
