# Generated by Django 4.1.5 on 2023-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0002_formdata_delete_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='formdata',
            name='mobile_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
