# Generated by Django 4.1.5 on 2023-05-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0003_category_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Service_list',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
