# Generated by Django 4.1.5 on 2023-05-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0004_remove_service_category_delete_service_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_by_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('service_time', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
