# Generated by Django 4.1.5 on 2023-05-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0004_formdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formdata',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
