# Generated by Django 4.1.5 on 2023-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0005_services_by_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
