# Generated by Django 4.1.5 on 2023-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0006_form_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='selected_services',
            field=models.CharField(default='', max_length=255),
        ),
    ]
