# Generated by Django 4.1.5 on 2023-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellitaweb', '0007_form_selected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
